import Header from "../Single Components/Header";
import Footer from "../Single Components/Footer";
import { Link } from "react-router-dom";
import { useState, useRef } from "react";

import EarnResults from "./EarnResults";
import EarnPageInputs from "./EarnPageInputs";
import MyHoldings from "./MyHoldings";

export default function EarnPage() {
  const [result, setResult] = useState(false);

  let amountOfMoney = useRef();
  let annualInvestment = useRef();
  let percentageChange = useRef();
  let amountOfYears = useRef();

  function handleGetResult(identifier, information) {
    if (information) {
      amountOfMoney.current = information.amountOfMoney;
      annualInvestment.current = information.annualInvestment;
      percentageChange.current = information.percentageChange;
      amountOfYears.current = information.amountOfYears;
    }

    setResult(identifier);
  }

  const information = {
    amountOfMoney: amountOfMoney.current,
    annualInvestment: annualInvestment.current,
    percentageChange: percentageChange.current,
    amountOfYears: amountOfYears.current,
  };

  return (
    <main className="w-full mt-16 min-h-screen text-white bg-[#1A1C22ff]">
      <div className="w-full bg-black h-auto flex flex-col items-center">
        <div className="w-[95%] xl:w-[80rem] py-24">
          <div className="flex justify-between items-center flex-col md:flex-row my-8">
            <p className="flex items-center gap-3 text-sm font-bold text-yellow-400 my-8">
              <Link to="/" className="cursor-pointer hover:underline">
                Home
              </Link>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="1em"
                height="1em"
                viewBox="0 0 24 24"
              >
                <path
                  fill="currentColor"
                  d="M9.879 17.243a1 1 0 0 1-.707-1.707L12.707 12L9.172 8.464a1 1 0 0 1 1.414-1.414l4.242 4.243a1 1 0 0 1 0 1.414l-4.242 4.243a.997.997 0 0 1-.707.293"
                />
              </svg>
              <p>Earn</p>
            </p>
          </div>
          <div className="flex justify-between flex-wrap gap-16 md:gap-5">
            <div>
              <h1 className="text-[5rem] font-semibold">Earn</h1>
              <p className="text-gray-300 text-2xl font-bold">
                Set up a{" "}
                <span className="text-yellow-400 underline">
                  plan to success
                </span>
                .
              </p>
              <p className="text-gray-400">
                See how much you would earn by looking at your made up possible
                outcomes!
              </p>
            </div>
            <MyHoldings />
          </div>
        </div>
      </div>
      <div className="w-full flex justify-center px-0 md:px-16">
        <div className="w-[95%] md:w-4/5 xl:w-3/5 py-24">
          <h1 className="text-4xl font-semibold tracking-[0.1rem] uppercase">
            Create your plan:
          </h1>
          <EarnPageInputs onResult={handleGetResult} />
        </div>
      </div>
      <div className="w-full flex justify-center">
        <div className="w-[95%] sm:w-[80%] h-auto md:w-4/5 xl:w-3/5 flex items-center border-[0.1rem] border-[#23272Eff] rounded-xl p-8 mb-32 flex-col md:flex-row">
          <div className="w-full sm:w-[100%] lg:w-[20%] grid place-content-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="5em"
              height="5em"
              viewBox="0 0 20 20"
            >
              <path
                fill="currentColor"
                fill-rule="evenodd"
                d="M10 1.944A11.954 11.954 0 0 1 2.166 5C2.056 5.649 2 6.319 2 7c0 5.225 3.34 9.67 8 11.317C14.66 16.67 18 12.225 18 7c0-.682-.057-1.35-.166-2.001A11.954 11.954 0 0 1 10 1.944M11 14a1 1 0 1 1-2 0a1 1 0 0 1 2 0m0-7a1 1 0 1 0-2 0v3a1 1 0 1 0 2 0z"
                clip-rule="evenodd"
              />
            </svg>
          </div>
          <h1 className="w-full sm:w-[100%] md:w-[80%] text-gray-400 text-center md:text-start">
            <strong>Disclaimer</strong>: The information provided in this tool
            is for educational and entertainment purposes only. Any investment
            decisions made based on the hypothetical outcomes generated by this
            tool are done so at your own risk. The projections and predictions
            presented here are purely speculative and should not be considered
            as financial advice. Actual investment outcomes may vary
            significantly from the simulated results. Always conduct thorough
            research and consult with a qualified financial advisor before
            making any investment decisions.
          </h1>
        </div>
      </div>
      {result && <EarnResults input={information} />}
    </main>
  );
}
